feat: derive tokenId from the ens domain
wealdtech/go-ens pull request #26
Opened 2022-09-19 08:57 UTC by tiennampham23

I see the [documetation](https://docs.ens.domains/dapp-developer-guide/ens-as-nft), the example is written by Javascript. So, I write the example with Go-ens

2022-09-19 09:04 UTC, mcdee requested changes
Thank you for this submission.  I have requested a few alterations, but nothing major.

2022-09-19 09:04 UTC, mcdee commented on tokenid.go
> +func DeriveTokenIdFromENSDomain(domain string) (string, error) {
I think this name can be shrunk to just `TokenID`; the rest is not adding a lot.

2022-09-19 09:04 UTC, mcdee commented on tokenid.go
> +	hash := fmt.Sprintf("0x%x", labelHash)
This format string could be written as `"%#x"`

2022-09-19 09:04 UTC, mcdee commented on tokenid.go
> +// DeriveTokenIdFromENSDomain derive token_id from the ENS domain
Would be good to have a bit more information about what the token ID is in the comment (specifically talk about it being the ERC-721 token ID).

2022-09-19 09:04 UTC, mcdee commented on tokenid_test.go
> +func TestDeriveTokenIdFromENSName(t *testing.T) {
Please could we add some tests that fail?  Empty domain, invalid domain, that type of thing.

2022-09-20 06:29 UTC, tiennampham23 commented
Hi @mcdee, I resolved your comments, please review my PR again.

2022-09-20 08:04 UTC, mcdee approved these changes
Looks good, thanks for the changes.

2022-09-20 08:05 UTC, merged